export const TYPES = {
  // Recipe types
  FETCH_RECIPE: 'FETCH_RECIPE',
  FETCH_RECIPES: 'FETCH_RECIPES',
  FETCH_FAVORITE_RECIPES: 'FETCH_FAVORITE_RECEIPES',

  // Event types
  FETCH_EVENTS: 'FETCH_EVENTS',

  // Login types
  UPDATE_FORM: 'UPDATE_FORM',
  SET_LOGGEDIN: 'SET_LOGGEDIN',
};
