export const TYPES = {
  // Recipe types
  FETCH_RECIPE: 'FETCH_RECIPE',
  FETCH_RECIPES: 'FETCH_RECIPES',
  FETCH_FAVORITE_RECIPES: 'FETCH_FAVORITE_RECEIPES',

  // Event types
  FETCH_EVENTS: 'FETCH_EVENTS',

  // Login types
  SET_LOGGEDIN: 'SET_LOGGEDIN',
  SET_LOGGEDOUT: 'SET_LOGGEDOUT',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_USER_ERROR: 'SET_USER_ERROR',

  // Friend types
  FETCH_FRIENDS: 'FETCH_FRIENDS',

  // User types
  FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
  EDIT_USER_DETAILS: 'EDIT_USER_DETAILS',
};
